export { ReactComponent as Logo} from "./logo.svg";
export { ReactComponent as BlueLogo} from "./blue.svg";
export { ReactComponent as Arrow} from "./arrow.svg";
export { ReactComponent as Profile} from "./profile.svg";
export { ReactComponent as ArrowLong} from "./arrow-fall.svg";
export { ReactComponent as RealisticLogo} from "./logo-3d.svg";
export { ReactComponent as BG_Light} from "./bg-light.svg";
export { ReactComponent as Curve} from "./Curve.svg";
export { ReactComponent as Pattern} from "./pattern.svg";
