export { ReactComponent as Logo} from "./logo.svg";
export { ReactComponent as BlueLogo} from "./blue.svg";
export { ReactComponent as Arrow} from "./arrow.svg";
export { ReactComponent as Profile} from "./profile.svg";
export { ReactComponent as ArrowLong} from "./arrow-fall.svg";
export { ReactComponent as RealisticLogo} from "./logo-3d.svg";
export { ReactComponent as BG_Light} from "./bg-light.svg";
export { ReactComponent as Curve} from "./Curve.svg";
export { ReactComponent as Pattern} from "./pattern.svg";
export { ReactComponent as Cross} from "./cross.svg";
export { ReactComponent as Search} from "./search.svg";
export { ReactComponent as TableHeader} from "./top-bottom.svg";
export { ReactComponent as ArrowDown} from "./arrow-down.svg";
export { ReactComponent as Clock} from "./clock.svg";
export { ReactComponent as Copy} from "./Copy.svg";
export { ReactComponent as Click} from "./icons8-галочка.svg";
export { ReactComponent as VaultsOn} from "./vaultsOn.svg";
export { ReactComponent as VaultsOff} from "./vaultsOff.svg";

